### ISSUE TITLE
Publish gradle plugin to Gradle plugin portal please.

### ISSUE THREAD

**Issue by grodin** [AhmedMourad0/no-copy#2]
It would be nice to have the plugin on the Gradle plugin portal, to simplify applying it slightly.

**Comment by AhmedMourad0** [comment]
Will look into that shortly.

**Comment by AhmedMourad0** [comment]
As of 1.2.0 the plugin is [now available](https://plugins.gradle.org/plugin/dev.ahmedmourad.nocopy.nocopy-gradle-plugin) at the Gradle Plugin Portal with the same group and artifact ids.

It also [requires Kotlin 1.4.20](https://github.com/AhmedMourad0/no-copy#versions)

Feel free to re-open this issue if you face any problems or have further feedback.

**Comment by grodin** [comment]
Fantastic! Thank you!
