### ISSUE TITLE
Add Support for Idea 2020.3

### ISSUE THREAD

**Issue by LukasPrediger** [AhmedMourad0/no-copy#4]
We are currently working on a project that will make heavy use of data classes with private constructors. Having this plugin would help make the code a lot cleaner, unfortunately the plugin does not currently support the newest version of Intellij Idea

**Comment by AhmedMourad0** [comment]
I've just released v1.3.0 which supports both Kotlin 1.4.32 and IDEA builds 203.*

The compiler plugin should be available in around 30 minutes, the IDEA plugin, however, needs to be reviewed by JB first, which usually takes less than 48 hours.

**Comment by AhmedMourad0** [comment]
The IDEA plugin should now be available to download/update.

Feel free to reopen this issue if you have any further problems.

**Comment by AhmedMourad0** [comment]
The IDEA plugin should now be available to download/update.

Feel free to reopen this issue if you have any further problems.
