### ISSUE TITLE
Add support for Android Studio Bumblebee 2021.1.1 Canary 2

### ISSUE THREAD

**Issue by Vasencheg** [AhmedMourad0/no-copy#5]

**Comment by AhmedMourad0** [comment]
I'll be looking into it very shortly.

**Comment by AhmedMourad0** [comment]
I've just released v1.4.0 of the IDEA plugin which supports all builds between 191.* and 212.*, which includes AS Bumblebee (211).

If you have any further feedback, please reopen this issue.
