### ISSUE TITLE
Question: Can we write our own method called copy() on a @NoCopy class?

### ISSUE THREAD

**Issue by ragnese** [AhmedMourad0/no-copy#6]
I haven't tried your plugin yet, but I'm planning on it. But I'd like to offer a copy() method of my own on my data class, that just excludes the troublesome properties, so that convenient altered-copies can still be made without risk of violating the invariants.

Thank you!

**Comment by AhmedMourad0** [comment]
Hi @ragnese,

Yes, you can overload the `copy` method by providing a different parameters list or a subset of the original one.
